services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
    volumes:
      - /etc/letsencrypt:/etc/nginx/certs:ro
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./volumes/nginx/www:/var/html/www/:ro
      - ./volumes/nginx/logs:/var/log/nginx:rw
    restart: unless-stopped
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data:rw
    restart: unless-stopped
    networks:
      - backend

  pgadmin:
    depends_on:
      - postgres
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin:rw
    restart: unless-stopped
    networks:
      - backend

  gogs:
    container_name: gogs
    image: gogs/gogs:latest
    env_file:
      - .env
    volumes:
      - ./volumes/gogs:/data:rw
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge
